name: Test Social News Site

on:
    workflow_dispatch:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    speak:
        runs-on: ubuntu-latest
        steps:
            - name: speak
              run: echo Social News Site!
        

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Test Social News Site
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                pytest